name: Build and Release Client

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write
  id-token: write

jobs:
  # ---------- Windows build ----------
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r windows_requirements.txt
          
      - name: Build executable
        if: runner.os == 'Windows'
        run: |
          pyinstaller main.py --noconsole --name "BazaarOracle" `
          --icon "assets\brand_icon.ico" --add-data "tools\windows_tesseract;tesseract" `
          --add-data "entities.json;."

      - name: Package Windows Release
        if: runner.os == 'Windows'
        run: |
          Compress-Archive -Path "dist/BazaarOracle/*" -DestinationPath "BazaarOracle-Windows.zip"

      - name: Create / update release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            BazaarOracle-Windows.zip
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false

  # ---------- macOS build ----------
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r mac_requirements.txt
          
      - name: Build executable
        if: runner.os == 'macOS'
        run: |
          pyinstaller main.py --noconsole --name "BazaarOracle" \
          --add-binary "tools/mac_tesseract/bin/tesseract:tools/mac_tesseract/bin" \
          --add-binary "tools/mac_tesseract/lib/*.dylib:tools/mac_tesseract/lib" \
          --add-data "tools/mac_tesseract/share/tessdata:tools/mac_tesseract/share/tessdata" \
          --add-data "entities.json:." \
          --icon "assets/brand_icon.ico"
      - name: Package macOS Release
        if: runner.os == 'macOS'
        run: |
          cd dist && zip -r ../BazaarOracle-macOS.zip "BazaarOracle.app"

      - name: Create / update release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            BazaarOracle-macOS.zip
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
